[build]
  publish = "dist"  # This should be "." if your build output is in the root directory
  command = "npm run build"  # Ensure this matches your build script

[build.environment]
  NODE_VERSION = "16"  # Matches the Node.js version in your package.json
